// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: busmgr.proto

// Package busmgr.v1 is the wire schema between a bus-mgr backend
// (e.g. ecu-zb) and inv-driver. Framing is a 4-byte BE length prefix
// per wire.MaxFrameBytes (64 KiB cap).

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role enumerates how a peer participates on the UDS. PUBLISHER (the
// default for backward compatibility) streams Hello + telemetry into
// the driver. SUBSCRIBER receives a fan-out of decoded upstream
// envelopes (telemetry today; raw frames after decode).
type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_PUBLISHER        Role = 1
	Role_SUBSCRIBER       Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "PUBLISHER",
		2: "SUBSCRIBER",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"PUBLISHER":        1,
		"SUBSCRIBER":       2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_busmgr_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_busmgr_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_busmgr_proto_rawDescGZIP(), []int{0}
}

// Envelope is the single top-level message on every frame. Tag
// numbers 1..9 are upstream (backend -> driver); 10..19 are reserved
// for downstream (driver -> backend) so adding upstream fields cannot
// collide with downstream additions.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_Hello
	//	*Envelope_Telemetry
	//	*Envelope_DecodeFailed
	//	*Envelope_RawFrame
	//	*Envelope_Info
	//	*Envelope_Send
	//	*Envelope_Broadcast
	//	*Envelope_Reset_
	//	*Envelope_SubscribeRaw
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_busmgr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_busmgr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_busmgr_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Envelope) GetTelemetry() *Telemetry {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Telemetry); ok {
			return x.Telemetry
		}
	}
	return nil
}

func (x *Envelope) GetDecodeFailed() *DecodeFailed {
	if x != nil {
		if x, ok := x.Body.(*Envelope_DecodeFailed); ok {
			return x.DecodeFailed
		}
	}
	return nil
}

func (x *Envelope) GetRawFrame() *RawFrame {
	if x != nil {
		if x, ok := x.Body.(*Envelope_RawFrame); ok {
			return x.RawFrame
		}
	}
	return nil
}

func (x *Envelope) GetInfo() *InverterInfo {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *Envelope) GetSend() *Send {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Send); ok {
			return x.Send
		}
	}
	return nil
}

func (x *Envelope) GetBroadcast() *Broadcast {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Broadcast); ok {
			return x.Broadcast
		}
	}
	return nil
}

func (x *Envelope) GetReset_() *Reset {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Reset_); ok {
			return x.Reset_
		}
	}
	return nil
}

func (x *Envelope) GetSubscribeRaw() *SubscribeRaw {
	if x != nil {
		if x, ok := x.Body.(*Envelope_SubscribeRaw); ok {
			return x.SubscribeRaw
		}
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type Envelope_Telemetry struct {
	Telemetry *Telemetry `protobuf:"bytes,2,opt,name=telemetry,proto3,oneof"`
}

type Envelope_DecodeFailed struct {
	DecodeFailed *DecodeFailed `protobuf:"bytes,3,opt,name=decode_failed,json=decodeFailed,proto3,oneof"`
}

type Envelope_RawFrame struct {
	RawFrame *RawFrame `protobuf:"bytes,4,opt,name=raw_frame,json=rawFrame,proto3,oneof"`
}

type Envelope_Info struct {
	Info *InverterInfo `protobuf:"bytes,5,opt,name=info,proto3,oneof"`
}

type Envelope_Send struct {
	Send *Send `protobuf:"bytes,10,opt,name=send,proto3,oneof"`
}

type Envelope_Broadcast struct {
	Broadcast *Broadcast `protobuf:"bytes,11,opt,name=broadcast,proto3,oneof"`
}

type Envelope_Reset_ struct {
	Reset_ *Reset `protobuf:"bytes,12,opt,name=reset,proto3,oneof"`
}

type Envelope_SubscribeRaw struct {
	SubscribeRaw *SubscribeRaw `protobuf:"bytes,13,opt,name=subscribe_raw,json=subscribeRaw,proto3,oneof"`
}

func (*Envelope_Hello) isEnvelope_Body() {}

func (*Envelope_Telemetry) isEnvelope_Body() {}

func (*Envelope_DecodeFailed) isEnvelope_Body() {}

func (*Envelope_RawFrame) isEnvelope_Body() {}

func (*Envelope_Info) isEnvelope_Body() {}

func (*Envelope_Send) isEnvelope_Body() {}

func (*Envelope_Broadcast) isEnvelope_Body() {}

func (*Envelope_Reset_) isEnvelope_Body() {}

func (*Envelope_SubscribeRaw) isEnvelope_Body() {}

// Hello is the first frame on every backend connection. The driver
// uses it to identify the bus backend (e.g. apsystems-stock-zb) and
// log version drift across restarts.
type Hello struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Backend     string                 `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"` // e.g. "apsystems-stock-zb"
	Version     string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // backend semver
	Hostname    string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	StartedAtMs int64                  `protobuf:"varint,4,opt,name=started_at_ms,json=startedAtMs,proto3" json:"started_at_ms,omitempty"` // unix ms
	// Free-form capability strings.
	BusCaps []string `protobuf:"bytes,5,rep,name=bus_caps,json=busCaps,proto3" json:"bus_caps,omitempty"`
	// Role declares the peer's intent. Unset (ROLE_UNSPECIFIED) is
	// treated as PUBLISHER by the server for backward compatibility.
	Role          Role `protobuf:"varint,6,opt,name=role,proto3,enum=busmgr.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_busmgr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_busmgr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_busmgr_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *Hello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Hello) GetStartedAtMs() int64 {
	if x != nil {
		return x.StartedAtMs
	}
	return 0
}

func (x *Hello) GetBusCaps() []string {
	if x != nil {
		return x.BusCaps
	}
	return nil
}

func (x *Hello) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

// RawFrame is a reassembled L1 reply that the driver decodes itself.
// peer_uid is intentionally omitted: it lives inside the L1 envelope
// and the driver parses it during decode. See codec.ParseL1.
type RawFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsMs          int64                  `protobuf:"varint,1,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`                // wall-clock at capture time
	ShortAddr     uint32                 `protobuf:"varint,2,opt,name=short_addr,json=shortAddr,proto3" json:"short_addr,omitempty"` // 16-bit network short address
	L1Frame       []byte                 `protobuf:"bytes,3,opt,name=l1_frame,json=l1Frame,proto3" json:"l1_frame,omitempty"`        // full reassembled L1 reply (FC FC … FE FE)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawFrame) Reset() {
	*x = RawFrame{}
	mi := &file_busmgr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawFrame) ProtoMessage() {}

func (x *RawFrame) ProtoReflect() protoreflect.Message {
	mi := &file_busmgr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawFrame.ProtoReflect.Descriptor instead.
func (*RawFrame) Descriptor() ([]byte, []int) {
	return file_busmgr_proto_rawDescGZIP(), []int{2}
}

func (x *RawFrame) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *RawFrame) GetShortAddr() uint32 {
	if x != nil {
		return x.ShortAddr
	}
	return 0
}

func (x *RawFrame) GetL1Frame() []byte {
	if x != nil {
		return x.L1Frame
	}
	return nil
}

// Telemetry is one decoded reply from one inverter. Mirrors
// codec.Reply plus a server-stamped ts_ms so the timeline doesn't
// depend on a synchronised clock between ECU and inv-driver hosts.
type Telemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsMs          int64                  `protobuf:"varint,1,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`                // wall-clock at publish time
	ShortAddr     uint32                 `protobuf:"varint,2,opt,name=short_addr,json=shortAddr,proto3" json:"short_addr,omitempty"` // 16-bit network short address
	PeerUid       string                 `protobuf:"bytes,3,opt,name=peer_uid,json=peerUid,proto3" json:"peer_uid,omitempty"`        // 12-char hex
	Cmd           uint32                 `protobuf:"varint,4,opt,name=cmd,proto3" json:"cmd,omitempty"`                              // L2 cmd (0xB1 QS1A, 0xBB DS3)
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`                           // "QS1A" / "DS3" / "unknown(0x..)"
	GridV         float64                `protobuf:"fixed64,6,opt,name=grid_v,json=gridV,proto3" json:"grid_v,omitempty"`
	BusV          float64                `protobuf:"fixed64,7,opt,name=bus_v,json=busV,proto3" json:"bus_v,omitempty"`
	FreqHz        float64                `protobuf:"fixed64,8,opt,name=freq_hz,json=freqHz,proto3" json:"freq_hz,omitempty"`
	ReportSec     uint32                 `protobuf:"varint,9,opt,name=report_sec,json=reportSec,proto3" json:"report_sec,omitempty"`
	ActivePowerW  float64                `protobuf:"fixed64,10,opt,name=active_power_w,json=activePowerW,proto3" json:"active_power_w,omitempty"`
	ReactiveVar   float64                `protobuf:"fixed64,11,opt,name=reactive_var,json=reactiveVar,proto3" json:"reactive_var,omitempty"`
	Panels        []*Panel               `protobuf:"bytes,12,rep,name=panels,proto3" json:"panels,omitempty"`
	LifetimeRaw   []uint64               `protobuf:"varint,13,rep,packed,name=lifetime_raw,json=lifetimeRaw,proto3" json:"lifetime_raw,omitempty"`
	LifetimeScale float64                `protobuf:"fixed64,14,opt,name=lifetime_scale,json=lifetimeScale,proto3" json:"lifetime_scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_busmgr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_busmgr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_busmgr_proto_rawDescGZIP(), []int{3}
}

func (x *Telemetry) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *Telemetry) GetShortAddr() uint32 {
	if x != nil {
		return x.ShortAddr
	}
	return 0
}

func (x *Telemetry) GetPeerUid() string {
	if x != nil {
		return x.PeerUid
	}
	return ""
}

func (x *Telemetry) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *Telemetry) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Telemetry) GetGridV() float64 {
	if x != nil {
		return x.GridV
	}
	return 0
}

func (x *Telemetry) GetBusV() float64 {
	if x != nil {
		return x.BusV
	}
	return 0
}

func (x *Telemetry) GetFreqHz() float64 {
	if x != nil {
		return x.FreqHz
	}
	return 0
}

func (x *Telemetry) GetReportSec() uint32 {
	if x != nil {
		return x.ReportSec
	}
	return 0
}

func (x *Telemetry) GetActivePowerW() float64 {
	if x != nil {
		return x.ActivePowerW
	}
	return 0
}

func (x *Telemetry) GetReactiveVar() float64 {
	if x != nil {
		return x.ReactiveVar
	}
	return 0
}

func (x *Telemetry) GetPanels() []*Panel {
	if x != nil {
		return x.Panels
	}
	return nil
}

func (x *Telemetry) GetLifetimeRaw() []uint64 {
	if x != nil {
		return x.LifetimeRaw
	}
	return nil
}

func (x *Telemetry) GetLifetimeScale() float64 {
	if x != nil {
		return x.LifetimeScale
	}
	return 0
}

// Panel mirrors codec.Panel.
type Panel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	DcV           float64                `protobuf:"fixed64,2,opt,name=dc_v,json=dcV,proto3" json:"dc_v,omitempty"`
	DcI           float64                `protobuf:"fixed64,3,opt,name=dc_i,json=dcI,proto3" json:"dc_i,omitempty"`
	W             float64                `protobuf:"fixed64,4,opt,name=w,proto3" json:"w,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Panel) Reset() {
	*x = Panel{}
	mi := &file_busmgr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Panel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Panel) ProtoMessage() {}

func (x *Panel) ProtoReflect() protoreflect.Message {
	mi := &file_busmgr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Panel.ProtoReflect.Descriptor instead.
func (*Panel) Descriptor() ([]byte, []int) {
	return file_busmgr_proto_rawDescGZIP(), []int{4}
}

func (x *Panel) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Panel) GetDcV() float64 {
	if x != nil {
		return x.DcV
	}
	return 0
}

func (x *Panel) GetDcI() float64 {
	if x != nil {
		return x.DcI
	}
	return 0
}

func (x *Panel) GetW() float64 {
	if x != nil {
		return x.W
	}
	return 0
}

// DecodeFailed records a frame the backend received but could not
// decode. Routed to events with kind=decode_failed.
type DecodeFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsMs          int64                  `protobuf:"varint,1,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	ShortAddr     uint32                 `protobuf:"varint,2,opt,name=short_addr,json=shortAddr,proto3" json:"short_addr,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	RawHex        string                 `protobuf:"bytes,4,opt,name=raw_hex,json=rawHex,proto3" json:"raw_hex,omitempty"` // may be truncated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeFailed) Reset() {
	*x = DecodeFailed{}
	mi := &file_busmgr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeFailed) ProtoMessage() {}

func (x *DecodeFailed) ProtoReflect() protoreflect.Message {
	mi := &file_busmgr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeFailed.ProtoReflect.Descriptor instead.
func (*DecodeFailed) Descriptor() ([]byte, []int) {
	return file_busmgr_proto_rawDescGZIP(), []int{5}
}

func (x *DecodeFailed) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *DecodeFailed) GetShortAddr() uint32 {
	if x != nil {
		return x.ShortAddr
	}
	return 0
}

func (x *DecodeFailed) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DecodeFailed) GetRawHex() string {
	if x != nil {
		return x.RawHex
	}
	return ""
}

// Send is a downstream stub. Server returns Unimplemented in v0.
type Send struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerUid       string                 `protobuf:"bytes,1,opt,name=peer_uid,json=peerUid,proto3" json:"peer_uid,omitempty"`
	Frame         []byte                 `protobuf:"bytes,2,opt,name=frame,proto3" json:"frame,omitempty"`
	DeadlineMs    int64                  `protobuf:"varint,3,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Send) Reset() {
	*x = Send{}
	mi := &file_busmgr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Send) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Send) ProtoMessage() {}

func (x *Send) ProtoReflect() protoreflect.Message {
	mi := &file_busmgr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Send.ProtoReflect.Descriptor instead.
func (*Send) Descriptor() ([]byte, []int) {
	return file_busmgr_proto_rawDescGZIP(), []int{6}
}

func (x *Send) GetPeerUid() string {
	if x != nil {
		return x.PeerUid
	}
	return ""
}

func (x *Send) GetFrame() []byte {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *Send) GetDeadlineMs() int64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

// Broadcast is a downstream stub. Server returns Unimplemented in v0.
type Broadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frame         []byte                 `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	DeadlineMs    int64                  `protobuf:"varint,2,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Broadcast) Reset() {
	*x = Broadcast{}
	mi := &file_busmgr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Broadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broadcast) ProtoMessage() {}

func (x *Broadcast) ProtoReflect() protoreflect.Message {
	mi := &file_busmgr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broadcast.ProtoReflect.Descriptor instead.
func (*Broadcast) Descriptor() ([]byte, []int) {
	return file_busmgr_proto_rawDescGZIP(), []int{7}
}

func (x *Broadcast) GetFrame() []byte {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *Broadcast) GetDeadlineMs() int64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

// Reset is a downstream stub. Server returns Unimplemented in v0.
type Reset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reset) Reset() {
	*x = Reset{}
	mi := &file_busmgr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reset) ProtoMessage() {}

func (x *Reset) ProtoReflect() protoreflect.Message {
	mi := &file_busmgr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reset.ProtoReflect.Descriptor instead.
func (*Reset) Descriptor() ([]byte, []int) {
	return file_busmgr_proto_rawDescGZIP(), []int{8}
}

// SubscribeRaw is a downstream stub. Server returns Unimplemented in
// v0. Shape is intentionally empty until requirements firm up.
type SubscribeRaw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRaw) Reset() {
	*x = SubscribeRaw{}
	mi := &file_busmgr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRaw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRaw) ProtoMessage() {}

func (x *SubscribeRaw) ProtoReflect() protoreflect.Message {
	mi := &file_busmgr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRaw.ProtoReflect.Descriptor instead.
func (*SubscribeRaw) Descriptor() ([]byte, []int) {
	return file_busmgr_proto_rawDescGZIP(), []int{9}
}

// InverterInfo carries identity and pair-state metadata sniffed off
// the primary ZigBee modem. Optional fields use proto3 'optional' so
// an unset field means "no update for this column" rather than "value
// is 0".
type InverterInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TsMs            int64                  `protobuf:"varint,1,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	PeerUid         string                 `protobuf:"bytes,2,opt,name=peer_uid,json=peerUid,proto3" json:"peer_uid,omitempty"` // 12-char hex
	ShortAddr       uint32                 `protobuf:"varint,3,opt,name=short_addr,json=shortAddr,proto3" json:"short_addr,omitempty"`
	ModelCode       *uint32                `protobuf:"varint,4,opt,name=model_code,json=modelCode,proto3,oneof" json:"model_code,omitempty"`
	SoftwareVersion *uint32                `protobuf:"varint,5,opt,name=software_version,json=softwareVersion,proto3,oneof" json:"software_version,omitempty"`
	Phase           *uint32                `protobuf:"varint,6,opt,name=phase,proto3,oneof" json:"phase,omitempty"` // 0 unknown, 1 single, 3 three
	ZigbeeBound     *bool                  `protobuf:"varint,7,opt,name=zigbee_bound,json=zigbeeBound,proto3,oneof" json:"zigbee_bound,omitempty"`
	TurnedOffRpt    *bool                  `protobuf:"varint,8,opt,name=turned_off_rpt,json=turnedOffRpt,proto3,oneof" json:"turned_off_rpt,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InverterInfo) Reset() {
	*x = InverterInfo{}
	mi := &file_busmgr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InverterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InverterInfo) ProtoMessage() {}

func (x *InverterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_busmgr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InverterInfo.ProtoReflect.Descriptor instead.
func (*InverterInfo) Descriptor() ([]byte, []int) {
	return file_busmgr_proto_rawDescGZIP(), []int{10}
}

func (x *InverterInfo) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *InverterInfo) GetPeerUid() string {
	if x != nil {
		return x.PeerUid
	}
	return ""
}

func (x *InverterInfo) GetShortAddr() uint32 {
	if x != nil {
		return x.ShortAddr
	}
	return 0
}

func (x *InverterInfo) GetModelCode() uint32 {
	if x != nil && x.ModelCode != nil {
		return *x.ModelCode
	}
	return 0
}

func (x *InverterInfo) GetSoftwareVersion() uint32 {
	if x != nil && x.SoftwareVersion != nil {
		return *x.SoftwareVersion
	}
	return 0
}

func (x *InverterInfo) GetPhase() uint32 {
	if x != nil && x.Phase != nil {
		return *x.Phase
	}
	return 0
}

func (x *InverterInfo) GetZigbeeBound() bool {
	if x != nil && x.ZigbeeBound != nil {
		return *x.ZigbeeBound
	}
	return false
}

func (x *InverterInfo) GetTurnedOffRpt() bool {
	if x != nil && x.TurnedOffRpt != nil {
		return *x.TurnedOffRpt
	}
	return false
}

var File_busmgr_proto protoreflect.FileDescriptor

const file_busmgr_proto_rawDesc = "" +
	"\n" +
	"\fbusmgr.proto\x12\tbusmgr.v1\"\xdc\x03\n" +
	"\bEnvelope\x12(\n" +
	"\x05hello\x18\x01 \x01(\v2\x10.busmgr.v1.HelloH\x00R\x05hello\x124\n" +
	"\ttelemetry\x18\x02 \x01(\v2\x14.busmgr.v1.TelemetryH\x00R\ttelemetry\x12>\n" +
	"\rdecode_failed\x18\x03 \x01(\v2\x17.busmgr.v1.DecodeFailedH\x00R\fdecodeFailed\x122\n" +
	"\traw_frame\x18\x04 \x01(\v2\x13.busmgr.v1.RawFrameH\x00R\brawFrame\x12-\n" +
	"\x04info\x18\x05 \x01(\v2\x17.busmgr.v1.InverterInfoH\x00R\x04info\x12%\n" +
	"\x04send\x18\n" +
	" \x01(\v2\x0f.busmgr.v1.SendH\x00R\x04send\x124\n" +
	"\tbroadcast\x18\v \x01(\v2\x14.busmgr.v1.BroadcastH\x00R\tbroadcast\x12(\n" +
	"\x05reset\x18\f \x01(\v2\x10.busmgr.v1.ResetH\x00R\x05reset\x12>\n" +
	"\rsubscribe_raw\x18\r \x01(\v2\x17.busmgr.v1.SubscribeRawH\x00R\fsubscribeRawB\x06\n" +
	"\x04body\"\xbb\x01\n" +
	"\x05Hello\x12\x18\n" +
	"\abackend\x18\x01 \x01(\tR\abackend\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\"\n" +
	"\rstarted_at_ms\x18\x04 \x01(\x03R\vstartedAtMs\x12\x19\n" +
	"\bbus_caps\x18\x05 \x03(\tR\abusCaps\x12#\n" +
	"\x04role\x18\x06 \x01(\x0e2\x0f.busmgr.v1.RoleR\x04role\"Y\n" +
	"\bRawFrame\x12\x13\n" +
	"\x05ts_ms\x18\x01 \x01(\x03R\x04tsMs\x12\x1d\n" +
	"\n" +
	"short_addr\x18\x02 \x01(\rR\tshortAddr\x12\x19\n" +
	"\bl1_frame\x18\x03 \x01(\fR\al1Frame\"\xa9\x03\n" +
	"\tTelemetry\x12\x13\n" +
	"\x05ts_ms\x18\x01 \x01(\x03R\x04tsMs\x12\x1d\n" +
	"\n" +
	"short_addr\x18\x02 \x01(\rR\tshortAddr\x12\x19\n" +
	"\bpeer_uid\x18\x03 \x01(\tR\apeerUid\x12\x10\n" +
	"\x03cmd\x18\x04 \x01(\rR\x03cmd\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x15\n" +
	"\x06grid_v\x18\x06 \x01(\x01R\x05gridV\x12\x13\n" +
	"\x05bus_v\x18\a \x01(\x01R\x04busV\x12\x17\n" +
	"\afreq_hz\x18\b \x01(\x01R\x06freqHz\x12\x1d\n" +
	"\n" +
	"report_sec\x18\t \x01(\rR\treportSec\x12$\n" +
	"\x0eactive_power_w\x18\n" +
	" \x01(\x01R\factivePowerW\x12!\n" +
	"\freactive_var\x18\v \x01(\x01R\vreactiveVar\x12(\n" +
	"\x06panels\x18\f \x03(\v2\x10.busmgr.v1.PanelR\x06panels\x12!\n" +
	"\flifetime_raw\x18\r \x03(\x04R\vlifetimeRaw\x12%\n" +
	"\x0elifetime_scale\x18\x0e \x01(\x01R\rlifetimeScaleJ\x04\b\x0f\x10\x10\"Q\n" +
	"\x05Panel\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x11\n" +
	"\x04dc_v\x18\x02 \x01(\x01R\x03dcV\x12\x11\n" +
	"\x04dc_i\x18\x03 \x01(\x01R\x03dcI\x12\f\n" +
	"\x01w\x18\x04 \x01(\x01R\x01w\"q\n" +
	"\fDecodeFailed\x12\x13\n" +
	"\x05ts_ms\x18\x01 \x01(\x03R\x04tsMs\x12\x1d\n" +
	"\n" +
	"short_addr\x18\x02 \x01(\rR\tshortAddr\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x17\n" +
	"\araw_hex\x18\x04 \x01(\tR\x06rawHex\"X\n" +
	"\x04Send\x12\x19\n" +
	"\bpeer_uid\x18\x01 \x01(\tR\apeerUid\x12\x14\n" +
	"\x05frame\x18\x02 \x01(\fR\x05frame\x12\x1f\n" +
	"\vdeadline_ms\x18\x03 \x01(\x03R\n" +
	"deadlineMs\"B\n" +
	"\tBroadcast\x12\x14\n" +
	"\x05frame\x18\x01 \x01(\fR\x05frame\x12\x1f\n" +
	"\vdeadline_ms\x18\x02 \x01(\x03R\n" +
	"deadlineMs\"\a\n" +
	"\x05Reset\"\x0e\n" +
	"\fSubscribeRaw\"\xf1\x02\n" +
	"\fInverterInfo\x12\x13\n" +
	"\x05ts_ms\x18\x01 \x01(\x03R\x04tsMs\x12\x19\n" +
	"\bpeer_uid\x18\x02 \x01(\tR\apeerUid\x12\x1d\n" +
	"\n" +
	"short_addr\x18\x03 \x01(\rR\tshortAddr\x12\"\n" +
	"\n" +
	"model_code\x18\x04 \x01(\rH\x00R\tmodelCode\x88\x01\x01\x12.\n" +
	"\x10software_version\x18\x05 \x01(\rH\x01R\x0fsoftwareVersion\x88\x01\x01\x12\x19\n" +
	"\x05phase\x18\x06 \x01(\rH\x02R\x05phase\x88\x01\x01\x12&\n" +
	"\fzigbee_bound\x18\a \x01(\bH\x03R\vzigbeeBound\x88\x01\x01\x12)\n" +
	"\x0eturned_off_rpt\x18\b \x01(\bH\x04R\fturnedOffRpt\x88\x01\x01B\r\n" +
	"\v_model_codeB\x13\n" +
	"\x11_software_versionB\b\n" +
	"\x06_phaseB\x0f\n" +
	"\r_zigbee_boundB\x11\n" +
	"\x0f_turned_off_rpt*;\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tPUBLISHER\x10\x01\x12\x0e\n" +
	"\n" +
	"SUBSCRIBER\x10\x02B'Z%github.com/bolke/inv-driver/wire;wireb\x06proto3"

var (
	file_busmgr_proto_rawDescOnce sync.Once
	file_busmgr_proto_rawDescData []byte
)

func file_busmgr_proto_rawDescGZIP() []byte {
	file_busmgr_proto_rawDescOnce.Do(func() {
		file_busmgr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_busmgr_proto_rawDesc), len(file_busmgr_proto_rawDesc)))
	})
	return file_busmgr_proto_rawDescData
}

var file_busmgr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_busmgr_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_busmgr_proto_goTypes = []any{
	(Role)(0),            // 0: busmgr.v1.Role
	(*Envelope)(nil),     // 1: busmgr.v1.Envelope
	(*Hello)(nil),        // 2: busmgr.v1.Hello
	(*RawFrame)(nil),     // 3: busmgr.v1.RawFrame
	(*Telemetry)(nil),    // 4: busmgr.v1.Telemetry
	(*Panel)(nil),        // 5: busmgr.v1.Panel
	(*DecodeFailed)(nil), // 6: busmgr.v1.DecodeFailed
	(*Send)(nil),         // 7: busmgr.v1.Send
	(*Broadcast)(nil),    // 8: busmgr.v1.Broadcast
	(*Reset)(nil),        // 9: busmgr.v1.Reset
	(*SubscribeRaw)(nil), // 10: busmgr.v1.SubscribeRaw
	(*InverterInfo)(nil), // 11: busmgr.v1.InverterInfo
}
var file_busmgr_proto_depIdxs = []int32{
	2,  // 0: busmgr.v1.Envelope.hello:type_name -> busmgr.v1.Hello
	4,  // 1: busmgr.v1.Envelope.telemetry:type_name -> busmgr.v1.Telemetry
	6,  // 2: busmgr.v1.Envelope.decode_failed:type_name -> busmgr.v1.DecodeFailed
	3,  // 3: busmgr.v1.Envelope.raw_frame:type_name -> busmgr.v1.RawFrame
	11, // 4: busmgr.v1.Envelope.info:type_name -> busmgr.v1.InverterInfo
	7,  // 5: busmgr.v1.Envelope.send:type_name -> busmgr.v1.Send
	8,  // 6: busmgr.v1.Envelope.broadcast:type_name -> busmgr.v1.Broadcast
	9,  // 7: busmgr.v1.Envelope.reset:type_name -> busmgr.v1.Reset
	10, // 8: busmgr.v1.Envelope.subscribe_raw:type_name -> busmgr.v1.SubscribeRaw
	0,  // 9: busmgr.v1.Hello.role:type_name -> busmgr.v1.Role
	5,  // 10: busmgr.v1.Telemetry.panels:type_name -> busmgr.v1.Panel
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_busmgr_proto_init() }
func file_busmgr_proto_init() {
	if File_busmgr_proto != nil {
		return
	}
	file_busmgr_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Hello)(nil),
		(*Envelope_Telemetry)(nil),
		(*Envelope_DecodeFailed)(nil),
		(*Envelope_RawFrame)(nil),
		(*Envelope_Info)(nil),
		(*Envelope_Send)(nil),
		(*Envelope_Broadcast)(nil),
		(*Envelope_Reset_)(nil),
		(*Envelope_SubscribeRaw)(nil),
	}
	file_busmgr_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_busmgr_proto_rawDesc), len(file_busmgr_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_busmgr_proto_goTypes,
		DependencyIndexes: file_busmgr_proto_depIdxs,
		EnumInfos:         file_busmgr_proto_enumTypes,
		MessageInfos:      file_busmgr_proto_msgTypes,
	}.Build()
	File_busmgr_proto = out.File
	file_busmgr_proto_goTypes = nil
	file_busmgr_proto_depIdxs = nil
}
