// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: recoveryd.proto

// Package recoveryd.v1 is the wire schema between a local client
// (ecu-web) and recoveryd, the daemon that owns the box's SSH access
// plane. Framing is the same 4-byte BE length prefix used by busmgr
// (wire.ReadFrame/WriteFrame, 64 KiB cap).

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AccessRequest is the single top-level message a client sends. Exactly
// one op is set per request.
type AccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*AccessRequest_ListKeys
	//	*AccessRequest_AddKey
	//	*AccessRequest_RemoveKey
	//	*AccessRequest_Status
	Op            isAccessRequest_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRequest) Reset() {
	*x = AccessRequest{}
	mi := &file_recoveryd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequest) ProtoMessage() {}

func (x *AccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recoveryd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequest.ProtoReflect.Descriptor instead.
func (*AccessRequest) Descriptor() ([]byte, []int) {
	return file_recoveryd_proto_rawDescGZIP(), []int{0}
}

func (x *AccessRequest) GetOp() isAccessRequest_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *AccessRequest) GetListKeys() *ListKeysOp {
	if x != nil {
		if x, ok := x.Op.(*AccessRequest_ListKeys); ok {
			return x.ListKeys
		}
	}
	return nil
}

func (x *AccessRequest) GetAddKey() *AddKeyOp {
	if x != nil {
		if x, ok := x.Op.(*AccessRequest_AddKey); ok {
			return x.AddKey
		}
	}
	return nil
}

func (x *AccessRequest) GetRemoveKey() *RemoveKeyOp {
	if x != nil {
		if x, ok := x.Op.(*AccessRequest_RemoveKey); ok {
			return x.RemoveKey
		}
	}
	return nil
}

func (x *AccessRequest) GetStatus() *StatusOp {
	if x != nil {
		if x, ok := x.Op.(*AccessRequest_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isAccessRequest_Op interface {
	isAccessRequest_Op()
}

type AccessRequest_ListKeys struct {
	ListKeys *ListKeysOp `protobuf:"bytes,1,opt,name=list_keys,json=listKeys,proto3,oneof"`
}

type AccessRequest_AddKey struct {
	AddKey *AddKeyOp `protobuf:"bytes,2,opt,name=add_key,json=addKey,proto3,oneof"`
}

type AccessRequest_RemoveKey struct {
	RemoveKey *RemoveKeyOp `protobuf:"bytes,3,opt,name=remove_key,json=removeKey,proto3,oneof"`
}

type AccessRequest_Status struct {
	Status *StatusOp `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

func (*AccessRequest_ListKeys) isAccessRequest_Op() {}

func (*AccessRequest_AddKey) isAccessRequest_Op() {}

func (*AccessRequest_RemoveKey) isAccessRequest_Op() {}

func (*AccessRequest_Status) isAccessRequest_Op() {}

// ListKeysOp returns the current key list and provider state.
type ListKeysOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysOp) Reset() {
	*x = ListKeysOp{}
	mi := &file_recoveryd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysOp) ProtoMessage() {}

func (x *ListKeysOp) ProtoReflect() protoreflect.Message {
	mi := &file_recoveryd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysOp.ProtoReflect.Descriptor instead.
func (*ListKeysOp) Descriptor() ([]byte, []int) {
	return file_recoveryd_proto_rawDescGZIP(), []int{1}
}

// AddKeyOp validates and appends an authorized key. The pubkey is the
// full OpenSSH single-line form (e.g. "ssh-ed25519 AAAA... comment").
// comment overrides any trailing comment in pubkey when non-empty.
type AddKeyOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        string                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddKeyOp) Reset() {
	*x = AddKeyOp{}
	mi := &file_recoveryd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddKeyOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKeyOp) ProtoMessage() {}

func (x *AddKeyOp) ProtoReflect() protoreflect.Message {
	mi := &file_recoveryd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKeyOp.ProtoReflect.Descriptor instead.
func (*AddKeyOp) Descriptor() ([]byte, []int) {
	return file_recoveryd_proto_rawDescGZIP(), []int{2}
}

func (x *AddKeyOp) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *AddKeyOp) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// RemoveKeyOp removes the key whose SHA256 fingerprint matches.
type RemoveKeyOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveKeyOp) Reset() {
	*x = RemoveKeyOp{}
	mi := &file_recoveryd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveKeyOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveKeyOp) ProtoMessage() {}

func (x *RemoveKeyOp) ProtoReflect() protoreflect.Message {
	mi := &file_recoveryd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveKeyOp.ProtoReflect.Descriptor instead.
func (*RemoveKeyOp) Descriptor() ([]byte, []int) {
	return file_recoveryd_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveKeyOp) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

// StatusOp returns provider/host-user/key-count without the full list.
type StatusOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusOp) Reset() {
	*x = StatusOp{}
	mi := &file_recoveryd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusOp) ProtoMessage() {}

func (x *StatusOp) ProtoReflect() protoreflect.Message {
	mi := &file_recoveryd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusOp.ProtoReflect.Descriptor instead.
func (*StatusOp) Descriptor() ([]byte, []int) {
	return file_recoveryd_proto_rawDescGZIP(), []int{4}
}

// SshKey is one authorized key in the list.
type SshKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pubkey is the normalised single-line OpenSSH form recoveryd renders
	// into authorized_keys.
	Pubkey string `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// Comment is the operator-facing label (key origin/owner).
	Comment string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	// AddedMs is the wall-clock add time in epoch milliseconds.
	AddedMs int64 `protobuf:"varint,3,opt,name=added_ms,json=addedMs,proto3" json:"added_ms,omitempty"`
	// Fingerprint is the ssh.FingerprintSHA256 of the key (the stable id
	// used by RemoveKeyOp).
	Fingerprint   string `protobuf:"bytes,4,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SshKey) Reset() {
	*x = SshKey{}
	mi := &file_recoveryd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SshKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SshKey) ProtoMessage() {}

func (x *SshKey) ProtoReflect() protoreflect.Message {
	mi := &file_recoveryd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SshKey.ProtoReflect.Descriptor instead.
func (*SshKey) Descriptor() ([]byte, []int) {
	return file_recoveryd_proto_rawDescGZIP(), []int{5}
}

func (x *SshKey) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *SshKey) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *SshKey) GetAddedMs() int64 {
	if x != nil {
		return x.AddedMs
	}
	return 0
}

func (x *SshKey) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

// AccessResponse is recoveryd's reply to any AccessRequest.
type AccessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Provider is the managed authorized_keys path (the source of truth).
	Provider string `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	// HostUser is the unix user that owns authorized_keys under the host
	// provider; empty when recoveryd writes as root.
	HostUser string `protobuf:"bytes,4,opt,name=host_user,json=hostUser,proto3" json:"host_user,omitempty"`
	// Keys is the full list (set on ListKeys; empty on Status).
	Keys []*SshKey `protobuf:"bytes,5,rep,name=keys,proto3" json:"keys,omitempty"`
	// KeyCount is the number of keys (always set).
	KeyCount      uint32 `protobuf:"varint,6,opt,name=key_count,json=keyCount,proto3" json:"key_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessResponse) Reset() {
	*x = AccessResponse{}
	mi := &file_recoveryd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessResponse) ProtoMessage() {}

func (x *AccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recoveryd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessResponse.ProtoReflect.Descriptor instead.
func (*AccessResponse) Descriptor() ([]byte, []int) {
	return file_recoveryd_proto_rawDescGZIP(), []int{6}
}

func (x *AccessResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AccessResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AccessResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AccessResponse) GetHostUser() string {
	if x != nil {
		return x.HostUser
	}
	return ""
}

func (x *AccessResponse) GetKeys() []*SshKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *AccessResponse) GetKeyCount() uint32 {
	if x != nil {
		return x.KeyCount
	}
	return 0
}

var File_recoveryd_proto protoreflect.FileDescriptor

const file_recoveryd_proto_rawDesc = "" +
	"\n" +
	"\x0frecoveryd.proto\x12\frecoveryd.v1\"\xef\x01\n" +
	"\rAccessRequest\x127\n" +
	"\tlist_keys\x18\x01 \x01(\v2\x18.recoveryd.v1.ListKeysOpH\x00R\blistKeys\x121\n" +
	"\aadd_key\x18\x02 \x01(\v2\x16.recoveryd.v1.AddKeyOpH\x00R\x06addKey\x12:\n" +
	"\n" +
	"remove_key\x18\x03 \x01(\v2\x19.recoveryd.v1.RemoveKeyOpH\x00R\tremoveKey\x120\n" +
	"\x06status\x18\x04 \x01(\v2\x16.recoveryd.v1.StatusOpH\x00R\x06statusB\x04\n" +
	"\x02op\"\f\n" +
	"\n" +
	"ListKeysOp\"<\n" +
	"\bAddKeyOp\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\tR\x06pubkey\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\"/\n" +
	"\vRemoveKeyOp\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\"\n" +
	"\n" +
	"\bStatusOp\"w\n" +
	"\x06SshKey\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\tR\x06pubkey\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12\x19\n" +
	"\badded_ms\x18\x03 \x01(\x03R\aaddedMs\x12 \n" +
	"\vfingerprint\x18\x04 \x01(\tR\vfingerprint\"\xb6\x01\n" +
	"\x0eAccessResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1b\n" +
	"\thost_user\x18\x04 \x01(\tR\bhostUser\x12(\n" +
	"\x04keys\x18\x05 \x03(\v2\x14.recoveryd.v1.SshKeyR\x04keys\x12\x1b\n" +
	"\tkey_count\x18\x06 \x01(\rR\bkeyCountB+Z)github.com/bolkedebruin/openaps/wire;wireb\x06proto3"

var (
	file_recoveryd_proto_rawDescOnce sync.Once
	file_recoveryd_proto_rawDescData []byte
)

func file_recoveryd_proto_rawDescGZIP() []byte {
	file_recoveryd_proto_rawDescOnce.Do(func() {
		file_recoveryd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recoveryd_proto_rawDesc), len(file_recoveryd_proto_rawDesc)))
	})
	return file_recoveryd_proto_rawDescData
}

var file_recoveryd_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_recoveryd_proto_goTypes = []any{
	(*AccessRequest)(nil),  // 0: recoveryd.v1.AccessRequest
	(*ListKeysOp)(nil),     // 1: recoveryd.v1.ListKeysOp
	(*AddKeyOp)(nil),       // 2: recoveryd.v1.AddKeyOp
	(*RemoveKeyOp)(nil),    // 3: recoveryd.v1.RemoveKeyOp
	(*StatusOp)(nil),       // 4: recoveryd.v1.StatusOp
	(*SshKey)(nil),         // 5: recoveryd.v1.SshKey
	(*AccessResponse)(nil), // 6: recoveryd.v1.AccessResponse
}
var file_recoveryd_proto_depIdxs = []int32{
	1, // 0: recoveryd.v1.AccessRequest.list_keys:type_name -> recoveryd.v1.ListKeysOp
	2, // 1: recoveryd.v1.AccessRequest.add_key:type_name -> recoveryd.v1.AddKeyOp
	3, // 2: recoveryd.v1.AccessRequest.remove_key:type_name -> recoveryd.v1.RemoveKeyOp
	4, // 3: recoveryd.v1.AccessRequest.status:type_name -> recoveryd.v1.StatusOp
	5, // 4: recoveryd.v1.AccessResponse.keys:type_name -> recoveryd.v1.SshKey
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_recoveryd_proto_init() }
func file_recoveryd_proto_init() {
	if File_recoveryd_proto != nil {
		return
	}
	file_recoveryd_proto_msgTypes[0].OneofWrappers = []any{
		(*AccessRequest_ListKeys)(nil),
		(*AccessRequest_AddKey)(nil),
		(*AccessRequest_RemoveKey)(nil),
		(*AccessRequest_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recoveryd_proto_rawDesc), len(file_recoveryd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_recoveryd_proto_goTypes,
		DependencyIndexes: file_recoveryd_proto_depIdxs,
		MessageInfos:      file_recoveryd_proto_msgTypes,
	}.Build()
	File_recoveryd_proto = out.File
	file_recoveryd_proto_goTypes = nil
	file_recoveryd_proto_depIdxs = nil
}
